/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import data.JPAUtil;

/**
 *
 * @author Luiz Henrique
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipal.class.getName());

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnAtalhoEmprestimo = new javax.swing.JButton();
        btnConsultarAcervo = new javax.swing.JButton();
        btnAtalhoDevolucao = new javax.swing.JButton();
        btnCadastrarVisitante = new javax.swing.JButton();
        barraDeMenuPrincipal = new javax.swing.JMenuBar();
        mCadastro = new javax.swing.JMenu();
        mItemConsultarAcervo = new javax.swing.JMenuItem();
        mItemConsultarPessoas = new javax.swing.JMenuItem();
        mItemLivros = new javax.swing.JMenuItem();
        mItemRevistas = new javax.swing.JMenuItem();
        mItemDvd = new javax.swing.JMenuItem();
        mItemPdf = new javax.swing.JMenuItem();
        mItemPeriodico = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        mItemVisitantes = new javax.swing.JMenuItem();
        mItemFuncionarios = new javax.swing.JMenuItem();
        mItemSair = new javax.swing.JMenuItem();
        mMovimentações = new javax.swing.JMenu();
        mItemRealizarEmprestimo = new javax.swing.JMenuItem();
        mItemRegistrarDevolucao = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Biblioteca");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("SISTEMA DE BIBLIOTECA");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Acesso Rápido.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        btnAtalhoEmprestimo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAtalhoEmprestimo.setText("Novo Empréstimo");
        btnAtalhoEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtalhoEmprestimoActionPerformed(evt);
            }
        });

        btnConsultarAcervo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConsultarAcervo.setText("Consultar Acervo");
        btnConsultarAcervo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarAcervoActionPerformed(evt);
            }
        });

        btnAtalhoDevolucao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAtalhoDevolucao.setText("Devolução");
        btnAtalhoDevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtalhoDevolucaoActionPerformed(evt);
            }
        });

        btnCadastrarVisitante.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCadastrarVisitante.setText("CadastrarVisitante");
        btnCadastrarVisitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarVisitanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAtalhoEmprestimo, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(btnAtalhoDevolucao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsultarAcervo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrarVisitante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(145, 145, 145))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtalhoEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarAcervo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtalhoDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        mCadastro.setText("Cadastros");

        mItemConsultarAcervo.setText("Consultar Acervo");
        mItemConsultarAcervo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemConsultarAcervoActionPerformed(evt);
            }
        });
        mCadastro.add(mItemConsultarAcervo);

        mItemConsultarPessoas.setText("Consultar Pessoas");
        mItemConsultarPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemConsultarPessoasActionPerformed(evt);
            }
        });
        mCadastro.add(mItemConsultarPessoas);

        mItemLivros.setText("Livro / Acervo");
        mItemLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemLivrosActionPerformed(evt);
            }
        });
        mCadastro.add(mItemLivros);

        mItemRevistas.setText("Revistas");
        mItemRevistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemRevistasActionPerformed(evt);
            }
        });
        mCadastro.add(mItemRevistas);

        mItemDvd.setText("DVDs");
        mItemDvd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemDvdActionPerformed(evt);
            }
        });
        mCadastro.add(mItemDvd);

        mItemPdf.setText("PDFs");
        mItemPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemPdfActionPerformed(evt);
            }
        });
        mCadastro.add(mItemPdf);

        mItemPeriodico.setText("Periódicos");
        mItemPeriodico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemPeriodicoActionPerformed(evt);
            }
        });
        mCadastro.add(mItemPeriodico);

        jMenuItem1.setText("Associado");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mCadastro.add(jMenuItem1);

        mItemVisitantes.setText("Visitantes");
        mItemVisitantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemVisitantesActionPerformed(evt);
            }
        });
        mCadastro.add(mItemVisitantes);

        mItemFuncionarios.setText("Funcionários");
        mItemFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemFuncionariosActionPerformed(evt);
            }
        });
        mCadastro.add(mItemFuncionarios);

        mItemSair.setText("Sair");
        mItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemSairActionPerformed(evt);
            }
        });
        mCadastro.add(mItemSair);

        barraDeMenuPrincipal.add(mCadastro);

        mMovimentações.setText("Movimentações");

        mItemRealizarEmprestimo.setText("Realizar Empréstimo");
        mItemRealizarEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemRealizarEmprestimoActionPerformed(evt);
            }
        });
        mMovimentações.add(mItemRealizarEmprestimo);

        mItemRegistrarDevolucao.setText("Registrar Devolução");
        mItemRegistrarDevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemRegistrarDevolucaoActionPerformed(evt);
            }
        });
        mMovimentações.add(mItemRegistrarDevolucao);

        barraDeMenuPrincipal.add(mMovimentações);

        setJMenuBar(barraDeMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(382, 382, 382)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemSairActionPerformed
        // Pergunta se quer mesmo sair (Opcional, mas elegante)
        int sair = javax.swing.JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?", "Sair", javax.swing.JOptionPane.YES_NO_OPTION);

        if (sair == javax.swing.JOptionPane.YES_OPTION) {
            // Fecha a conexão com o banco antes de morrer (Boa prática!)
            try {
                JPAUtil.close();
            } catch (Exception e) {
                // Ignora erro no fechamento
            }

            // Encerra a JVM (Mata o programa)
            System.exit(0);
        }
    }//GEN-LAST:event_mItemSairActionPerformed

    private void mItemRealizarEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemRealizarEmprestimoActionPerformed
        TelaRealizarEmprestimo tela = new TelaRealizarEmprestimo();
        tela.setVisible(true);
    }//GEN-LAST:event_mItemRealizarEmprestimoActionPerformed

    private void mItemLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemLivrosActionPerformed
        // Cria e abre a tela de cadastro
        TelaCadastroLivro tela = new TelaCadastroLivro();
        tela.setVisible(true);
        // tela.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE); // Opcional: fecha só a janela, não o programa
    }//GEN-LAST:event_mItemLivrosActionPerformed

    private void mItemVisitantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemVisitantesActionPerformed
        TelaCadastroVisitante tela = new TelaCadastroVisitante();
        tela.setVisible(true);
    }//GEN-LAST:event_mItemVisitantesActionPerformed

    private void mItemRevistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemRevistasActionPerformed
        TelaCadastroRevista tela = new TelaCadastroRevista();
        tela.setVisible(true);
    }//GEN-LAST:event_mItemRevistasActionPerformed

    private void mItemDvdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemDvdActionPerformed
        TelaCadastroDVD tela = new TelaCadastroDVD();
        tela.setVisible(true);
    }//GEN-LAST:event_mItemDvdActionPerformed

    private void mItemPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemPdfActionPerformed
        TelaCadastroPDF tela = new TelaCadastroPDF();
        tela.setVisible(true);
    }//GEN-LAST:event_mItemPdfActionPerformed

    private void mItemRegistrarDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemRegistrarDevolucaoActionPerformed
        TelaDevolucao tela = new TelaDevolucao();
        tela.setVisible(true);
    }//GEN-LAST:event_mItemRegistrarDevolucaoActionPerformed

    private void mItemConsultarAcervoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemConsultarAcervoActionPerformed
        TelaConsultarAcervo tela = new TelaConsultarAcervo();
        tela.setVisible(true);
    }//GEN-LAST:event_mItemConsultarAcervoActionPerformed

    private void mItemFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemFuncionariosActionPerformed
        TelaCadastroFuncionario tela = new TelaCadastroFuncionario();
        tela.setVisible(true);
    }//GEN-LAST:event_mItemFuncionariosActionPerformed

    private void mItemPeriodicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemPeriodicoActionPerformed
        TelaCadastroPeriodico tela = new TelaCadastroPeriodico();
        tela.setVisible(true);
    }//GEN-LAST:event_mItemPeriodicoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        TelaCadastroAssociado tela = new TelaCadastroAssociado();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mItemConsultarPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemConsultarPessoasActionPerformed
        TelaConsultarPessoas tela = new TelaConsultarPessoas();
        tela.setVisible(true);
    }//GEN-LAST:event_mItemConsultarPessoasActionPerformed

    private void btnAtalhoDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtalhoDevolucaoActionPerformed
        TelaDevolucao tela = new TelaDevolucao();
        tela.setVisible(true);
    }//GEN-LAST:event_btnAtalhoDevolucaoActionPerformed

    private void btnConsultarAcervoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarAcervoActionPerformed
        TelaConsultarAcervo tela = new TelaConsultarAcervo();
        tela.setVisible(true);
    }//GEN-LAST:event_btnConsultarAcervoActionPerformed

    private void btnCadastrarVisitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarVisitanteActionPerformed
        TelaCadastroVisitante tela = new TelaCadastroVisitante();
        tela.setVisible(true);
    }//GEN-LAST:event_btnCadastrarVisitanteActionPerformed

    private void btnAtalhoEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtalhoEmprestimoActionPerformed
        TelaRealizarEmprestimo tela = new TelaRealizarEmprestimo();
        tela.setVisible(true);
    }//GEN-LAST:event_btnAtalhoEmprestimoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraDeMenuPrincipal;
    private javax.swing.JButton btnAtalhoDevolucao;
    private javax.swing.JButton btnAtalhoEmprestimo;
    private javax.swing.JButton btnCadastrarVisitante;
    private javax.swing.JButton btnConsultarAcervo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu mCadastro;
    private javax.swing.JMenuItem mItemConsultarAcervo;
    private javax.swing.JMenuItem mItemConsultarPessoas;
    private javax.swing.JMenuItem mItemDvd;
    private javax.swing.JMenuItem mItemFuncionarios;
    private javax.swing.JMenuItem mItemLivros;
    private javax.swing.JMenuItem mItemPdf;
    private javax.swing.JMenuItem mItemPeriodico;
    private javax.swing.JMenuItem mItemRealizarEmprestimo;
    private javax.swing.JMenuItem mItemRegistrarDevolucao;
    private javax.swing.JMenuItem mItemRevistas;
    private javax.swing.JMenuItem mItemSair;
    private javax.swing.JMenuItem mItemVisitantes;
    private javax.swing.JMenu mMovimentações;
    // End of variables declaration//GEN-END:variables
}
