/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Luiz Henrique
 */
public class TelaDevolucao extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaDevolucao.class.getName());

    /**
     * Creates new form TelaDevolucao
     */
    public TelaDevolucao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTelaDevolucao = new javax.swing.JLabel();
        jlIdEmprestimo = new javax.swing.JLabel();
        txtIdEmprestimo = new javax.swing.JTextField();
        btfDevolver = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jlCpf = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlTelaDevolucao.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jlTelaDevolucao.setText("Tela de Devolução");

        jlIdEmprestimo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlIdEmprestimo.setText("ID do Item a ser devolvido: ");

        txtIdEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdEmprestimoActionPerformed(evt);
            }
        });

        btfDevolver.setText("DEVOLVER");
        btfDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btfDevolverActionPerformed(evt);
            }
        });

        btnVoltar.setText("VOLTAR");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jlCpf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlCpf.setText("CPF: ");

        txtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 339, Short.MAX_VALUE)
                .addComponent(btfDevolver, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(241, 241, 241))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(430, 430, 430)
                        .addComponent(jlTelaDevolucao))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlCpf)
                                .addGap(136, 136, 136)
                                .addComponent(txtCpf))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlIdEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtIdEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jlTelaDevolucao)
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlIdEmprestimo)
                    .addComponent(txtIdEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCpf)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btfDevolver)
                    .addComponent(btnVoltar))
                .addGap(84, 84, 84))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdEmprestimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdEmprestimoActionPerformed

    private void btfDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btfDevolverActionPerformed
        // 1. Pegar o ID
        String idTexto = txtIdEmprestimo.getText();

        if (idTexto.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Digite o ID do empréstimo!");
            return;
        }

        int idEmp = 0;
        try {
            idEmp = Integer.parseInt(idTexto);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "O ID deve ser um número!");
            return;
        }

        // 2. Verificar se existe e se está aberto
        dao.EmprestimoDAO dao = new dao.EmprestimoDAO();
        entities.Emprestimo emp = dao.buscarPorId(idEmp);

        if (emp == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Empréstimo não encontrado!");
            dao.fechar();
            return;
        }

        if (emp.getStatus() == false) { // false = já fechado/devolvido
            javax.swing.JOptionPane.showMessageDialog(this, "Este empréstimo já foi devolvido anteriormente!");
            dao.fechar();
            return;
        }

        // 3. Confirmar Visualmente
        int confirmacao = javax.swing.JOptionPane.showConfirmDialog(this,
                "Confirmar devolução do item:\n"
                + emp.getDocumento().getNome() + "?",
                "Devolução", javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirmacao == javax.swing.JOptionPane.YES_OPTION) {
            // 4. Efetivar a devolução
            dao.finalizarEmprestimo(idEmp); // O método que criamos no DAO que seta data de hoje e status false
            javax.swing.JOptionPane.showMessageDialog(this, "Item devolvido com sucesso!");
            txtIdEmprestimo.setText("");
        }

        dao.fechar();
    }//GEN-LAST:event_btfDevolverActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void txtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaDevolucao().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btfDevolver;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jlCpf;
    private javax.swing.JLabel jlIdEmprestimo;
    private javax.swing.JLabel jlTelaDevolucao;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtIdEmprestimo;
    // End of variables declaration//GEN-END:variables
}
