/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Luiz Henrique
 */
public class TelaRealizarEmprestimo extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaRealizarEmprestimo.class.getName());

    /**
     * Creates new form TelarealizarEmprestimo
     */
    public TelaRealizarEmprestimo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlRealizarEmpresitmo = new javax.swing.JLabel();
        jlIDItem = new javax.swing.JLabel();
        txtIdItem = new javax.swing.JTextField();
        jlCpfUsuario = new javax.swing.JLabel();
        txtCpfUsuario = new javax.swing.JTextField();
        btnConfirmar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlRealizarEmpresitmo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jlRealizarEmpresitmo.setText("Realizar Empréstimos");

        jlIDItem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlIDItem.setText("ID do Item: (Livro, DVD, Revista, etc.)");

        jlCpfUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlCpfUsuario.setText("CPF do Usuário:");

        txtCpfUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfUsuarioActionPerformed(evt);
            }
        });

        btnConfirmar.setText("CONFIRMAR EMPRÉSTIMO");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnVoltar.setText("VOLTAR");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlCpfUsuario)
                                .addGap(154, 154, 154)
                                .addComponent(txtCpfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlIDItem)
                                .addGap(18, 18, 18)
                                .addComponent(txtIdItem))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(395, 395, 395)
                        .addComponent(jlRealizarEmpresitmo)))
                .addContainerGap(476, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jlRealizarEmpresitmo)
                .addGap(124, 124, 124)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlIDItem)
                    .addComponent(txtIdItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCpfUsuario)
                    .addComponent(txtCpfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        //Pegar dados da tela
        String idTexto = txtIdItem.getText();
        String cpf = txtCpfUsuario.getText();

        if (idTexto.isEmpty() || cpf.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Preencha o ID e o CPF!");
            return;
        }

        int idItem = 0;
        try {
            idItem = Integer.parseInt(idTexto);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "O ID deve ser um número!");
            return;
        }

        //Verificar se o ITEM existe
        dao.DocumentoDAO docDAO = new dao.DocumentoDAO();
        entities.Documento itemEncontrado = docDAO.buscarPorId(idItem);
        docDAO.fechar();

        if (itemEncontrado == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Item não encontrado com o ID: " + idItem);
            return;
        }
        dao.EmprestimoDAO checkDAO = new dao.EmprestimoDAO();
        if (!checkDAO.isDocumentoDisponivel(idItem)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "ERRO: O item '" + itemEncontrado.getNome() + "' já está emprestado!");
            checkDAO.fechar();
            return; // Para tudo aqui e não deixa salvar
        }
        checkDAO.fechar();
        
        
        dao.VisitanteDAO visitDAO = new dao.VisitanteDAO();
        entities.Visitante pessoaEncontrada = visitDAO.buscarPorCpf(cpf);
        visitDAO.fechar();

        if (pessoaEncontrada == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "CPF não cadastrado!");
            return;
        }

        //Confirmação e Salvamento (Resto do código que já existia...)
        int confirmacao = javax.swing.JOptionPane.showConfirmDialog(this,
                "Emprestar: " + itemEncontrado.getNome() + "\nPara: " + pessoaEncontrada.getNome() + "?",
                "Confirmar", javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirmacao == javax.swing.JOptionPane.YES_OPTION) {
            try {
                //Cria o empréstimo com data de hoje
                entities.Emprestimo novo = new entities.Emprestimo(
                        itemEncontrado,
                        cpf,
                        java.time.LocalDate.now(),
                        java.time.LocalDate.now().plusDays(7)
                );

                dao.EmprestimoDAO daoSalvar = new dao.EmprestimoDAO();
                daoSalvar.salvar(novo);
                daoSalvar.fechar();

                javax.swing.JOptionPane.showMessageDialog(this, "Sucesso!");
                txtIdItem.setText("");
                txtCpfUsuario.setText("");

            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // Fecha a janela atual e libera a memória
        // Como a TelaPrincipal ainda está aberta no fundo, o usuário "volta" para ela.
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void txtCpfUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaRealizarEmprestimo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jlCpfUsuario;
    private javax.swing.JLabel jlIDItem;
    private javax.swing.JLabel jlRealizarEmpresitmo;
    private javax.swing.JTextField txtCpfUsuario;
    private javax.swing.JTextField txtIdItem;
    // End of variables declaration//GEN-END:variables
}
