/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Luiz Henrique
 */
public class TelaLogin extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaLogin.class.getName());

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlLogin = new javax.swing.JLabel();
        jlMatricula = new javax.swing.JLabel();
        jlSenha = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlLogin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlLogin.setText("LOGIN");

        jlMatricula.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlMatricula.setText("Matricula: ");

        jlSenha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlSenha.setText("Senha: ");

        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });

        btnEntrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEntrar.setText("ENTRAR");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlMatricula)
                    .addComponent(jlSenha))
                .addGap(174, 174, 174)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtMatricula)
                        .addComponent(txtSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addComponent(jlLogin))))
                .addContainerGap(354, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jlLogin)
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlMatricula))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSenha)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94)
                .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        // 1. Capturar dados
        String matricula = txtMatricula.getText();
        String senha = new String(txtSenha.getPassword()); // PasswordField retorna char[], convertemos para String

        // Validação básica de campo vazio
        if (matricula.isEmpty() || senha.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Preencha matrícula e senha!");
            return;
        }

        // 2. Tentar autenticar no Banco
        try {
            dao.FuncionarioDAO dao = new dao.FuncionarioDAO();
            entities.Funcionario func = dao.autenticar(matricula, senha); // Método que criamos antes
            dao.fechar();

            if (func != null) {
                // --- LOGIN SUCESSO! ---
                // 1. Abre a tela principal
                TelaPrincipal principal = new TelaPrincipal();
                principal.setVisible(true);

                // 2. Fecha a tela de login
                this.dispose();

            } else {
                // --- LOGIN FALHOU ---
                javax.swing.JOptionPane.showMessageDialog(this, "Matrícula ou Senha inválidos!");
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro de conexão: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            // Configura o tema FlatLaf (Visual Moderno)
            com.formdev.flatlaf.FlatDarkLaf.setup();
        } catch (Exception ex) {
            System.err.println("Falha ao iniciar o tema FlatLaf.");
        }

        // -----------------------------------
        //CRIA UM ADMIN PADRÃO 
        // -----------------------------------
        try {
            // Instancia o DAO
            dao.FuncionarioDAO dao = new dao.FuncionarioDAO();

            // Verifica se o usuário "admin" já existe
            entities.Funcionario admin = dao.buscarPorMatricula("admin");

            // Se retornou null, significa que não existe. Vamos criar!
            if (admin == null) {
                System.out.println(">>> Banco vazio detectado. Criando usuário Admin padrão...");

                // Cria o objeto (Nome, CPF, Email, Celular, Matrícula, Senha)
                // USE CPFs e DADOS FICTÍCIOS QUE PASSEM NA SUA REGRA DE BANCO
                entities.Funcionario novoAdmin = new entities.Funcionario(
                        "Administrador do Sistema",
                        "000.000.000-00",
                        "admin@sistema.com",
                        "(00) 0000-0000",
                        "admin", // <--- LOGIN
                        "admin" // <--- SENHA
                );

                dao.salvar(novoAdmin);
                System.out.println(">>> Usuário Admin criado com sucesso!");
            } else {
                System.out.println(">>> Usuário Admin já existe. Pulando criação.");
            }

            dao.fechar();

        } catch (Exception e) {
            // Se der erro (ex: banco fora do ar), avisa no console mas tenta abrir a tela
            System.err.println("Erro ao verificar admin: " + e.getMessage());
            // e.printStackTrace(); 
        }
        // -------------------------------------------------------

        /* Abre a janela de Login */
        java.awt.EventQueue.invokeLater(() -> {
            TelaLogin tela = new TelaLogin();
            tela.setLocationRelativeTo(null);
            tela.setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel jlLogin;
    private javax.swing.JLabel jlMatricula;
    private javax.swing.JLabel jlSenha;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
